char dungeon3[50][200] = {
  {"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT  Legend:"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T  T = Tree"},
  {"T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT  P = Dead Body"},
  {"T          T    C   T    G      T        T      G   T        T          T         T        T          T        T          T        T          T       T  U = Looted Body"},
  {"T        T   T    T   T      T   T    T   T      T   T    T   T      T   T     T   T     T  T      T   T    T   T      T   T    T   T      T   T     T"},
  {"T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTT TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T"},
  {"T       T       T       T  C    T       T       TG      T       T    T       T       T       T       T       T       T       T       T       T       T"},
  {"T          T     G  T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT"},
  {"T     C    TG       T       G  T   C    T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T        T   T    T   T      T   T    T   T      T   T    T   T      T   T     T   T     T  T      T   T    T   T      T   T    T   T      T   T     T"},
  {"T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTT TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T"},
  {"T       T       T       T       T       T       T       T       T    T       T       T       T       T       T       T       T       T       T       T"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T        T   T    T   T      T   T    T   T      T   T    T   T      T   T     T   T     T  T      T   T    T   T      T   T    T   T      T   T     T"},
  {"T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTT TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T"},
  {"T       T       T       T       T       T       T       T       T    T       T       T       T       T       T       T       T       T       T       T"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T        T   T    T   T      T   T    T   T      T   T    T   T      T   T     T   T     T  T      T   T    T   T      T   T    T   T      T   T     T"},
  {"T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTT TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T"},
  {"T       T       T       T       T       T       T       T       T    T       T       T       T       T       T       T       T       T       T       T"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T        T   T    T   T      T   T    T   T      T   T    T   T      T   T     T   T     T  T      T   T    T   T      T   T    T   T      T   T     T"},
  {"T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTT TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T"},
  {"T       T       T       T       T       T       T       T       T    T       T       T       T       T       T       T       T       T       T       T"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T        T   T    T   T      T   T    T   T      T   T    T   T      T   T     T   T     T  T      T   T    T   T      T   T    T   T      T   T     T"},
  {"T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTT TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T"},
  {"T       T       T       T       T       T       T       T       T    T       T       T       T       T       T       T       T       T       T       T"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T        T   T    T   T      T   T    T   T      T   T    T   T      T   T     T   T     T  T      T   T    T   T      T   T    T   T      T   T     T"},
  {"T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTT TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T"},
  {"T       T       T       T       T       T       T       T       T    T       T       T       T       T       T       T       T       T       T       T"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTT T TTTTTTT  T  TTTTTT"},
  {"T          T        T          T        T          T        T          T         T        T          T        T          T        T          T       T"},
  {"T        T   T    T   T      T   T    T   T      T   T    T   T      T   T     T   T     T  T      T   T    T   T      T   T    T   T      T   T     T"},
  {"T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTT TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T TTTTT T"},
  {"T       T       T       T       T       T       T       T       T    T       T       T       T       T       T       T       T       T       T       T"},
  {"TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTEEETTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"}};
