char dungeon4[37][200] = {
{"      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"},
{"    WWWWWWWWWWW        TTTT  TT   WWWWW              WWW        WWW"},
{"  WWW  C  WW          TTTT TTT  C  WWWWWWW         WWWW           WWW    "},
{"WWW      WW              TTT       WWWW         WWWWWWWWW           WWW"},
{"W       WWW                         WWWW       WWWW      WWWW         W   "},    
{"W        WW                        WWWW         WWWWW     WWWWWW      W"},
{"W        WWW          WW          WWWWW          WWWWWW  WWWWW        W"},
{"W        WWWW        WWWW          WWW            WWWWWWWWW           W"},
{"W         WW          WWWW         WWWW                               W"},
{"W          WWW           WW           WWW                             W"},
{"W        WWW             WWW            WWW                           W"},
{"W       WWW       G       WW      G                                   W"},
{"W       WWWW             WWWW                                         W"},
{"W        WWW            WWWW            WWWWWWWWWWWWW                 W"},
{"W       WWWW           WW           WWWWWWWW                          E"},    
{"W        WWW          WWW          WWWWWW                 G           E"},
{"W         WW          WWW          WWWW                               E"},
{"W        WWW          WWW             WWWW                            W"},
{"W         WWW          WW            WWWWWWW                          W"},
{"W        WWWW          WWW              WWWWWWWWW                     W"},
{"W         WWW           WW                                      TTT   W"},
{"W          WWW          WWW                                    TTTTT  W"},
{"W           WW           WW        TTTT       WWWWWWWW          TTTT  W"},
{"W           WW           WWW         TTTT       WWW           TTTT    W"},
{"W           WWW           WWW          TT        WWWWWWWWW      TT    W"},
{"W            WWW           WWWWW                    WWWWWWWW          W"},
{"W            WW                WWWWWW                    WWWWWW  C  WWW"},
{"W            WW                    WWWW        G                WWWWWWW"},
{"W           WWW                     WWW                         WWWWWWW"},
{"W           WWW          WW          WW                             WWW"},
{"W           WWWW         WWW        WWWWW  TTT    WWW T               W"},
{"W            WWW        WWW           WWW  T  WWWWW  TTT              W"},
{"W                      WW      G       WWW   WWWW                     W"},
{"WWW                     WWW            WWWWWWWWW                    WWW"},
{"  WWW        TTT         WWWW            WWW  C                    WWW"},
{"    WWW    TTTT          WWW                                     WWW"},
{"      WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW     "}};
