char dungeon1[25][100] =
{{"WWWWWWWWWWEEEEEWWWWWWWWWW  Welcome to GAME NAME! A D&D inspired Roguelike."},
{"W        +      W   C   W  You awken in a dark prision. You are unsure how you have ended up here."},
{"W        +B    CW   G   W  Below you will see the map of the current dungeon you find yourself in."},
{"W        +      W  ---  W  Movement: WASD, View your Inventory with I"},
{"W         WWWWWWW-------W  Legend: W = Wall, * = Character, C = Chest, D = Door,"},
{"W               W       W  ' ' = Open Space, G = Bad Guy, - = Line of Sight, _ = Bed,"},
{"WWWWWWWWWW     W        W  B = Boss, P = Dead Person, U = Open Chest, E = Exit, T = Table,"},
{"W CCCCC  W     WWWW  WWWW  + = Boss Line of Sight"},
{"W        W              W  Don't die. The game is hardcore mode."},
{"W    G---D     W        W"},
{"W        W     W        W"},
{"W__    __W     W TTTTTT W"},
{"WWWWWWWWWW    GWWWWWWWWWW"},
{"W___C    W   --W        W"},
{"W___C    D  ---D   TT   W"},
{"W___C    W ----W   TT   W"},
{"W___C    W-----W   TT   W"},
{"W___C    D-----D   TT   W"},
{"W___C    W-----W        W"},
{"WWWWWWWWWW     WWWWWWWWWW"},
{"W                       W"},
{"WWWDWWWWWDWWWWWDWWWWWDWWW"},
{"W     W     W     W     W"},
{"W     W  C  W  P  W C   W"},
{"WWWWWWWWWWWWWWWWWWWWWWWWW"}};
