char dungeon5[36][200] = {
{"WWWWWWWWWWWWWWwwwWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"},
{"                                             WWWWWWWWWWWWW"},
{"                                    WWWWWWWW     OOOOO   WWWW"},
{"                                WWWWWWWW //   OOOOOOOOOOOO   WW"},
{"                         WWWWWWWWWWWWW ///   OOOOOOOOOOOOOO   WWWWW"},
{"                 WWWWWWWWWWWWWWWWWWWWW //   OOOOOOOOOOOOOOOO  /// WWWWW "},
{"W           WWWWWWWWWWWWWWWWWWWWWWWWW  ///   OOOOOOOOOOOOO   /// WWWWWWWWWW "},
{"W WWWWWWWEEEEWWWWWWWWWWWWWWWWWWWWWWWWW  ///   OOOOOOOOOO   ///  WWWWWWWWWWWWW"},
{"WWWWWWWWWWW    WWWWWWWWWWWWWWWWWWWWWWWWW  ///   OOOOO   ////  WWWWWWWWWWWWWWWWW    "},                                     
{"WWWWWWWWWW       +++++++       WWWWWWWWWWWW  //////////  WWWWWWWWWWWWWWWWWWWWWWW"},
{"WWWWWWWW        ++++B++++        WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"},
{"WWWWWWWW         +++++++          WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"},
{"WWWWWWWW          +++++           WWWWWWWWWWWWWWWWWWWWWWWWW            WWWWWWWWW"},
{"WWWWWWWWWW         +++                 wwwwwwwwwwwwwwwwww      C        WWWWWWWW"},
{"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW        wwwwwwwwwwwww                   WWWWWWWW"},
{"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW        wwwwwwww         WWWW          WWWWWWW"},
{"WWWWWWWWWWW       C    WWWWWWWWWWWWW                   WWWWWWWG          WWWWWWW"},
{"WWWWWWW                    WWWWWWWWWW               WWWWWWWWW  G         WWWWWWW"},
{"WWWW                         WWWWWWWWW          WWWWWWWWWW     W        WWWWWWWW"},
{"WWWW           G             WWWWWWWWWWWWWWWWWWWWWWWW        WWW      _WWWWWWWWW"},
{"WWWWWW                     WWWWWWWWWWWWWWWWWWWWWW          WWWW       WWWWWWWWWW"},
{"WWWWWWWWWW        WWWWW                                WWWWWW        WWWWWWWWWWW"},
{"WWWWWWWWWWWWWW       WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW          WWWWWWWWWWWWW"},
{"WWWWWWWWWWWWWWWWW     WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW           WWWWWWWWWWWWWWWW"},
{"WWWWWWWWWWWWWWWWWW      G                                   WWWWWWWWWWWWWWWWWWWW"},
{"W  C   WWWWWWWW         WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW   C    W"},
{"W       WWWWW         WWWWWW      WWWWWW     WWWWWW      WWWWWW      WWWWWW    W"},
{"WW        WWWWW         WW    G     WW         WW          WW          WWWWWW  W"},
{"WWW        WWWWW              WW          WW          WW          WW     WWWW  W"},
{"WWWW        WWWWWWWWW       WWWWWW      WWWWWW      WWWWWW      WWWWWW       GWW"},
{"WWWWW            WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW      WWW"},
{"WWWW                 WWWWWWWWWWWW             WWWWWWWWWWWW            WWW     WW"},
{"WWW       WWWW         WWWWWWW         G        WWWWWW                  WW     W"},
{"W        WWWWWWW                   WWWWWWW                  WWWWWWW      WW    W"},
{"W S     WWWWWWWWWW               WWWWWWWWWW               WWWWWWWWWW          _W"},
{"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"}};
