char dungeon2[40][200] = {
{"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW  Legend:"},
{"W       WWWWWWWWWWWW                W        W        W       WWWWWWWWWWWW     W  W = Wall"},
{"W       WWWWWWWWWWWW                W        W        W       WWWWWWWWWWWW     W  C = Chest"},
{"W       WW   C    WW                W        W        W       WW    C   WW     W  U = Open Chest/Looted Body"},
{"W       WWW      WWW       WWWWWWWWWW        WWWWWWWWWW       WWW      WWW     W  P = Dead Body"},
{"W        W        W        W                          W        W        W      W  T = Tree"},
{"W        W        W        W                          W        W        W      W  G = Guard"},
{"W        W        W        W        WWWWWWWWWW        W        W        W      W  - = Line of Sight"},
{"W        W        WWWWWWWWWW        W        W        WWWWWWWWWW        W      W  * = Character"},
{"W        W                          W        W                          W      W"},
{"W       W                           W        W                          W      W"},
{"W      W                            W        W                          W      W"},
{"W     W           WWWWWWWWWW        WW      WW       WWWWWWWWWW          W     W"},
{"W    W           W         W         WW    WW        W         W          W    W"},
{"W   W           W    C     W          WW  WW         W    C     W          W   W"},
{"W  W           W  ------ WWW         - WWWW          WWW         W          W  W"},
{"W W           W    -----WWWW         --              WWWW         W          W W"},
{"WW           W     G                 ---                    G     W           WW"},
{"W           W                        ----G                         W            W"},    
{"W           W      G                 ---                    G     W            W"},
{"WW           W          WWWW         --              WWWW         W           WW"},
{"W W           W          WWW         -               WWW           W          W W"},  
{"W  W           W           W           WWWW           W          W           W W"},
{"W   W           W    C     W          WW  WW          W    C    W           W  W"},
{"W    W           W         W         WW    WW         W        W           W   W"},
{"W     W            WWWWWWWWW   G    WW      WW    G   WWWWWWWWW           W    W"},
{"W      W                           WW        WW                           W    W"},
{"W       W                          WW        WW                          W     W"},
{"W        W                         WW        WW                          W     W"},
{"W        W        WWWWWWWWWW       WW        WW        WWWWWWWWWW        W     W"},
{"W        W        WWWWWWWWWW       WW        WW        WW   C            W     W"},
{"W        W        WWWWWWWWWWWWWWWWWWW        WWWWWWWWWWWWWWWWWWWW        W     W"},
{"W        W                         WW        WW                          W     W"},
{"W        W        WWWWWWWWWW       WW        WW      WWWWWWWWWW        W       W"},
{"W        W    G   W        W       WW        WW      W        W   G    W       W"},
{"W       WWW      WWW       W       WW        WW      W       WWW      WWW      W"},
{"W       WW    C   WW       W       WWWWWWWWWWWW      W       WW   C    WW      W"},
{"W       WWWWWWWWWWWW       W         G      G        W       WWWWWWWWWWWW      W"},
{"W       WWWWWWWWWWWW       W         G      G        W       WWWWWWWWWWWW      W"},
{"WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW  E  WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW"}};
